networkservicemesh/sdk-vpp

.golangci.yml, go.mod, go.sum, pkg/networkservice/mechanisms/kernel/README.md, pkg/networkservice/mechanisms/kernel/client.go, pkg/networkservice/mechanisms/kernel/common.go, pkg/networkservice/mechanisms/kernel/kerneltap/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go, pkg/networkservice/mechanisms/kernel/server.go
=> Fix af_packet kernel mechanism.

pkg/networkservice/mechanisms/kernel/kerneltap/common.go
=> Remember to store link in metadata for tapv2

pkg/networkservice/chains/xconnectns/server.go
https://github.com/networkservicemesh/sdk/pull/585
=> Update client factory according to the new connect

go.mod, go.sum, pkg/networkservice/connectioncontext/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontext/ipcontext/routes/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go, pkg/networkservice/mechanisms/memif/common.go, pkg/networkservice/mechanisms/vxlan/common.go, pkg/networkservice/mechanisms/vxlan/vxlanacl/common.go, pkg/networkservice/tag/common.go, pkg/networkservice/up/common.go, pkg/networkservice/xconnect/l2xconnect/common.go
=> Update to new logger usage

go.mod, go.sum, pkg/networkservice/connectioncontext/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontext/ipcontext/routes/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go, pkg/networkservice/mechanisms/memif/common.go, pkg/networkservice/mechanisms/vxlan/common.go, pkg/networkservice/mechanisms/vxlan/vxlanacl/common.go, pkg/networkservice/tag/common.go, pkg/networkservice/up/common.go, pkg/networkservice/xconnect/l2xconnect/common.go
=> Update to latest sdk version

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
=> ci: add cmd-nsc-vpp and cmd-nse-icmp-responder-vpp to dependent repositories

go.mod, go.sum, pkg/networkservice/chains/xconnectns/server.go, pkg/networkservice/stats/doc.go, pkg/networkservice/stats/server.go
This PR provides new stats chain element that retrieves vpp interfaces traffic statistic.
=> Add stats chain element

pkg/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go
Resolves networkservicemesh/cmd-forwarder-vpp#66
=> Add short circuit paths

go.mod, go.sum, pkg/networkservice/chains/xconnectns/server.go
Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>
=> Update to latest sdk

pkg/networkservice/mechanisms/memif/common.go
=> Add memif L3-mode support

go.mod, go.sum, pkg/networkservice/chains/xconnectns/server.go
Closes https://github.com/networkservicemesh/sdk-vpp/pull/259.
=> Manually update to the latest sdk version

pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go
=> Fix kernelvethpair chain element on restore

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
=> feat: Add release actions for sdk-vpp

.github/workflows/ci.yaml, .golangci.yml, pkg/networkservice/connectioncontext/ipcontext/routes/client.go, pkg/networkservice/mechanisms/kernel/kerneltap/client.go
=> Fix linter issues

pkg/networkservice/acl/common.go
Fixes mirroring for egress rules in acl creation
=> Hot fix for acl chain element

.github/workflows/update-dependent-repositories-gomod.yaml
=> Fix: added firewall nse to github workflow

pkg/networkservice/mechanisms/kernel/client.go, pkg/networkservice/mechanisms/kernel/constants.go, pkg/networkservice/mechanisms/kernel/server.go
#270 
This reverts commit 4a704af372298c9ca6fab4f684e1289813af2274.
=> Revert "Temporarily disable tapv2. (#269)"

pkg/networkservice/mechanisms/kernel/kernelvethpair/ipneighbor/common.go
=> ipneighbor fix to work with refresh

pkg/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/networkservice/connectioncontextkernel/mtu/client.go, pkg/networkservice/connectioncontextkernel/mtu/common.go, pkg/networkservice/connectioncontextkernel/mtu/server.go, pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go, pkg/tools/mechutils/mechutils.go
https://github.com/networkservicemesh/sdk-vpp/issues/254
=> Replace ToInterfaceName with GetInterfaceName

pkg/networkservice/mechanisms/kernel/kerneltap/client.go, pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kerneltap/server.go
Closes https://github.com/networkservicemesh/sdk-vpp/issues/320
=> Add logs for delete operation into kerneltap server

go.mod, go.sum
Issues:
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/284
https://github.com/networkservicemesh/sdk-vpp/issues/348
=> Upgrade to VPP v21.06

pkg/networkservice/mechanisms/memif/memifproxy/client.go
https://github.com/networkservicemesh/deployments-k8s/issues/2822
=> Change back socketFileURL before next call

go.mod, go.sum
Signed-off-by: Vladimir Popov <vladimir.popov@xored.com>
=> Manually update to the latest govpp version

go.mod, go.sum, pkg/networkservice/chains/xconnectns/server.go
=> Adapt to networkservicemesh/sdk#1083

pkg/networkservice/connectioncontext/ipcontext/ipaddress/client.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/option.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/server.go
=> Add WithLoadSwIfIndex option to ipaddress

pkg/networkservice/chains/forwarder/doc.go, pkg/networkservice/chains/forwarder/server.go
=> p2mp: Update xconnects to be able to discover nses

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
=> [sdk-vpp] add cmd-nse-vlan-vpp repo as dependent repo

pkg/networkservice/chains/forwarder/server.go
https://github.com/networkservicemesh/integration-k8s-kind/pull/454
=> qfix: Remove clienturl from chains/forwarder

pkg/networkservice/chains/forwarder/server.go
https://github.com/networkservicemesh/integration-k8s-kind/runs/4157539095
=> fix: Add filtermechanisms client for chain/forwarder

go.mod, go.sum, pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/mechanisms/vlan/client.go, pkg/networkservice/mechanisms/vlan/common.go, pkg/networkservice/mechanisms/vlan/doc.go, pkg/networkservice/mechanisms/vlan/hwaddress/client.go, pkg/networkservice/mechanisms/vlan/hwaddress/common.go, pkg/networkservice/mechanisms/vlan/hwaddress/doc.go, pkg/networkservice/mechanisms/vlan/l2vtr/client.go, pkg/networkservice/mechanisms/vlan/l2vtr/common.go, pkg/networkservice/mechanisms/vlan/l2vtr/constants.go, pkg/networkservice/mechanisms/vlan/l2vtr/doc.go
This PR contains the remote vlan mechanism support enhancement for vpp.
Related PR: api#112
=> Add vlan remote mechanism support

pkg/networkservice/mechanisms/vxlan/client.go, pkg/networkservice/mechanisms/vxlan/common.go, pkg/networkservice/mechanisms/vxlan/server.go
=> Added more logs

pkg/networkservice/mechanisms/kernel/kernelvethpair/server.go
Fixes: https://github.com/networkservicemesh/integration-k8s-gke/issues/228
There is no need to create `vethpair` before `next.Request()`
=> qfix: Change vethpair creation logic

pkg/networkservice/acl/server.go
Removed recreation of acl rules on each request, and added additional cleanup on close
This prevents acl rules creation on each and every request (refresh/heal)
Closes https://github.com/networkservicemesh/deployments-k8s/issues/2879
Unblocks https://github.com/networkservicemesh/deployments-k8s/pull/3663
=> Fix for acl server

.github/workflows/release.yaml
=> qfix: Add missed cmd-nse-firewall-vpp to release action

pkg/networkservice/mechanisms/wireguard/peer/common.go
Issue: https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/1
=> Fix wireguard allowedIPs

pkg/networkservice/mechanisms/memif/common.go
Issue: networkservicemesh/sdk#1196
For example, `NSMgr + NSE` died. Forwarder doesn't know about NSE death and doesn't receive `Close` from the client (because NSMgr is also died). But it stores `ifindex` in metadata that belongs to the old NSE interface.
We need to additionally check the interface by `SocketFilename` and delete it if we find the old one.
=> Fix memif mechanism for healing cases

pkg/networkservice/mechanisms/vlan/common.go
Fix SwInterfaceDump filtering for interface name in case of remote vlan mechanism (#494)
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> Fix SwInterfaceDump filtering for interface name in case of rvlan (#494)

go.mod, go.sum, pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go, pkg/tools/link/metadata.go
Closes: https://github.com/networkservicemesh/sdk-vpp/pull/496
=> Fix after netlink update

pkg/networkservice/chains/forwarder/server.go
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
=> qfix: Add sendfdreg client into forwarder's client

pkg/networkservice/tag/common.go, pkg/networkservice/tag/server.go
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/512
=> [qfix] Fix typos in tag chain element

pkg/networkservice/connectioncontext/ipcontext/routes/common.go, pkg/networkservice/vrf/common.go, pkg/networkservice/vrf/doc.go, pkg/networkservice/vrf/metadata.go, pkg/networkservice/vrf/option.go, pkg/networkservice/vrf/server.go, pkg/tools/ifindex/type.go
Closes https://github.com/networkservicemesh/sdk-vpp/pull/368
Closes https://github.com/networkservicemesh/sdk-vpp/issues/341
=> feat: add vrf chain element for vl3 nses

pkg/networkservice/connectioncontext/ipcontext/unnumbered/client.go, pkg/networkservice/connectioncontext/ipcontext/unnumbered/common.go, pkg/networkservice/connectioncontext/ipcontext/unnumbered/doc.go, pkg/networkservice/connectioncontext/ipcontext/unnumbered/metadata.go, pkg/networkservice/connectioncontext/ipcontext/unnumbered/server.go
Closes https://github.com/networkservicemesh/sdk-vpp/pull/385
Closes https://github.com/networkservicemesh/sdk-vpp/issues/374
=> feat: add unnumbered chain element

pkg/networkservice/vrf/common.go
=> [qfix] Fix vfr panic

pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/mechanisms/memif/client.go, pkg/networkservice/nsmonitor/client.go, pkg/networkservice/nsmonitor/client_test.go, pkg/networkservice/nsmonitor/doc.go, pkg/networkservice/nsmonitor/monitor.go, pkg/networkservice/nsmonitor/option.go, pkg/networkservice/nsmonitor/utlis.go
Related to https://github.com/networkservicemesh/sdk/issues/1187
=> netns monitor

pkg/networkservice/loopback/client.go
=> [qfix] Add postpone ctx to loopback

pkg/networkservice/loopback/common.go, pkg/networkservice/vrf/client.go, pkg/networkservice/vrf/common.go, pkg/networkservice/vrf/option.go, pkg/networkservice/vrf/server.go
=> Fixes for loopback and VRF chain elements

go.mod, go.sum, pkg/networkservice/chains/forwarder/server.go
Closes: https://github.com/networkservicemesh/sdk-vpp/pull/579
=> Update registry client

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Issue: https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/issues/1
=> Add cmd-nse-simple-vl3-docker to dependent repositories

.github/workflows/automerge.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/pr-for-updates.yaml, .github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml, pkg/tools/proxy/proxy_test.go
https://github.com/networkservicemesh/.github/issues/4
=> Reusable workflows

pkg/networkservice/mechanisms/wireguard/peer/common.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/6488
=> wireguard: add 0.0.0.0/0 as allowed IPs

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> Fix dependent repositories

pkg/networkservice/chains/forwarder/options.go, pkg/networkservice/chains/forwarder/server.go
Continuation of https://github.com/networkservicemesh/sdk/pull/1384
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/638
=> Add prioritymechanisms chain element to forwarder

go.mod, go.sum
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/802
=> Update vpp version

pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/common.go
`AfPacketCreate` doesn't work on the latest vpp version. Replace with `AfPacketCreateV3`
Default RxMode is `interrupt`
https://github.com/networkservicemesh/integration-k8s-gke/pull/362
=> Change af_packet API version

pkg/networkservice/chains/forwarder/server.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9218
=> Add pinggrouprange to forwarder's chain

.golangci.yml, go.mod, go.sum, pkg/networkservice/connectioncontext/ipcontext/unnumbered/client.go, pkg/networkservice/connectioncontext/ipcontext/unnumbered/metadata.go, pkg/networkservice/connectioncontext/ipcontext/unnumbered/server.go, pkg/networkservice/nsmonitor/client_test.go, pkg/networkservice/nsmonitor/utlis.go, pkg/networkservice/pinhole/client.go
https://github.com/networkservicemesh/deployments-k8s/issues/9216
=> Update to go 1.20

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9210
=> Add cmd-lb-vl3-vpp to dependent repos

pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/mechanisms/ipsec/client.go, pkg/networkservice/mechanisms/ipsec/common.go, pkg/networkservice/mechanisms/ipsec/options.go, pkg/networkservice/mechanisms/ipsec/server.go
Closes: https://github.com/networkservicemesh/sdk-vpp/issues/745
=> Fix IPSec key generation

pkg/networkservice/pinhole/common.go
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/953
=> Fix pinhole panic in case of error

pkg/tools/heal/liveness_check.go
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/289
=> Pass interface index to VPP ping API

pkg/networkservice/mechanisms/kernel/kerneltap/common.go
According to the tests results (iperf3 was used) with the default ring size, we have the same bitrate, but 4 times less memory usage.
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/1047
=> tap: use default ring size

pkg/networkservice/chains/forwarder/server.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/11372
=> Pass missing dial timeout option

pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/nsmonitor/client.go
https://github.com/networkservicemesh/integration-k8s-kind/pull/1013
=> Revert nsmonitor + add additional checks to prevent random connection closes

pkg/networkservice/nsmonitor/client.go
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/1129
=> Fix context leak in `nsmonitor` chain element

pkg/networkservice/chains/forwarder/server.go
https://github.com/networkservicemesh/sdk/pull/1710
=> Disable heal and retry in registry clients of forwarder

pkg/networkservice/metrics/stats/client.go, pkg/networkservice/metrics/stats/common.go, pkg/networkservice/metrics/stats/prometheus.go, pkg/networkservice/metrics/stats/server.go
https://github.com/networkservicemesh/sdk/issues/1652
This PR refactors the Prometheus metrics to collect data on a per-connection basis, improving observability and enabling more fine-grained monitoring.
=> Refactor Prometheus metrics to collect per-connection data
