pkg/networkservice/chains/xconnectns/server.go
VPP forwarder sends file received from NSE as a `/proc/${pid}/fd/${fd}` to NSMgr. Such `pid/fd` pair is incorrect for NSMgr so it fails to send such file to the next hop.
```
Feb 19 05:43:27.617 [INFO] [name:nsmgr-k4mhq] (1) ⎆ sdk/pkg/networkservice/common/authorize/authorizeServer.Close() span=3ba9b39f56cf5f50:180a70f91b5184e6:3ba9b39f56cf5f50:1
Feb 19 05:43:27.617 [INFO] [name:nsmgr-k4mhq] (1.1)   request={"id":"b34e2416-0187-4785-8e8e-38464235f87f","network_service":"icmp-responder","mechanism":{"cls":"LOCAL","type":"KERNEL","parameters":{"inodeURL":"file:///proc/7/fd/16"}} ...
...
Feb 19 05:43:27.633 [INFO] [name:nsmgr-k4mhq] (25)                         ⎆ sdk/pkg/networkservice/common/mechanisms/sendfd/sendFDClient.Close() span=3ba9b39f56cf5f50:466e31146a990130:7a4a19874a65cfb9:1
Feb …
```
=> Add sendfd.NewClient() to xconnectns chain

pkg/networkservice/chains/xconnectns/server.go
Signed-off-by: Artem Belov <artem.belov@xored.com>
=> Fix heal update

pkg/networkservice/connectioncontext/ipcontext/routes/client.go
**Description**
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/954
When `routesClient.Close()` is invoked because of SIGNAL, `vpp` process may already be killed. So, we cannot delete routes in this case, the chain of Closes is interrupted and will not be called on the next items.
**Solution**
Call `.Close()` before deleting routes.
=> Fix routesClient on Close

go.mod, go.sum, pkg/networkservice/chains/xconnectns/server.go
Both client and server chain elements make decisions and set parameters (say for mechanisms)
on the downward path of the call chain, and take action on the return path of the call chain.
For this reason, pinhole should open a 'pinhole' in any ACL *before* on the return chain
before the mechanism takes action to create a remote mechanism.
For vxlan this doesn't matter, as it is stateless.
For wireguard, which sends an initiator message on peer creation, it matters a lot.
If pinhole is misplaced (as it was previously), wireguard's initial initiator message
that is sent on peer creation is blocked as there is no pinhole for it.  Retries occur
after 5 seconds.  If pinhole is properly placed in the chain (as in this PR), then the initial
initiator message goes out, and the wireguard tunnel …
=> Move pinhole to after the mechanism chain elements in both client and server.

pkg/networkservice/mechanisms/memif/client.go, pkg/networkservice/mechanisms/memif/server.go
Turns out this was causing a heisenbug.  Fixed.
=> Fix order of memif cleanup on close.

pkg/networkservice/mechanisms/kernel/kerneltap/client.go, pkg/networkservice/mechanisms/kernel/kerneltap/server.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/server.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/server.go, pkg/networkservice/mechanisms/vxlan/client.go, pkg/networkservice/mechanisms/vxlan/server.go, pkg/networkservice/xconnect/l2xconnect/client.go, pkg/networkservice/xconnect/l3xconnect/client.go
Close should always cleanup *first*, then call next.
Close should never stop calling next just because its local cleanup failed.
=> More fixes for order of operations

pkg/networkservice/chains/xconnectns/server.go, pkg/networkservice/mechanisms/memif/common.go, pkg/networkservice/mechanisms/memif/metatdata.go, pkg/networkservice/mechanisms/memif/option.go, pkg/networkservice/mechanisms/memif/server.go
Refactored memif chain element and made separate element which supports direct memif logic
fixes https://github.com/networkservicemesh/sdk-vpp/issues/287
=> Fix for direct memif logic

go.mod, go.sum, pkg/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/networkservice/connectioncontextkernel/mtu/common.go, pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go
=> Manual api update

pkg/networkservice/connectioncontext/ipcontext/ipaddress/common.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/metadata.go
#306
Save the IP-addresses assigned to the interface. 
We cannot call `.SwInterfaceAddDelAddress(...)` on refresh again, because vpp generates an error.
=> Save the IP-addresses assigned to the interface

.golangci.yml, pkg/networkservice/mechanisms/vxlan/mtu/common.go, pkg/networkservice/mechanisms/wireguard/mtu/common.go, pkg/networkservice/pinhole/common.go, pkg/networkservice/up/common.go, pkg/networkservice/up/peerup/common.go
Closes VPP dump clients to prevent memory leaks.
https://github.com/networkservicemesh/deployments-k8s/issues/2381
=> [qfix] Close VPP dump clients

pkg/networkservice/mechanisms/memif/memifproxy/proxy_listener.go
Fixes error handling in `memifproxy`.
If `err` is not `*net.OpError` it doesn't return and passes `nil` `in` further in `copy` method.
Found in https://github.com/networkservicemesh/deployments-k8s/issues/2381#issuecomment-940120379 logs:
[forwarder_old_8.zip](https://github.com/networkservicemesh/deployments-k8s/files/7322924/forwarder_old_8.zip)
=> [qfix] Fix error handling in memifproxy

pkg/networkservice/up/client.go, pkg/networkservice/up/common.go, pkg/networkservice/up/option.go, pkg/networkservice/up/server.go
=> Add WithLoadSwIfIndex option to up chain element

pkg/networkservice/chains/forwarder/server.go
Since forwarders connect to endpoints we need to prevent connection to dead nses as soon as possible with dialTimeout.
=> qfix: Add dial timeout for chains/forwarder

pkg/networkservice/mechanisms/kernel/kernelvethpair/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/mtu/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/mtu/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/mtu/doc.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/mtu/server.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/server.go
This *probably* fixes:
https://github.com/networkservicemesh/sdk/issues/1148
The underlying issue was that the end of the vethpair to which
VPP was attaching with afpacket was not getting its MTU set correctly.
As a result, if an oversized packet was sent over it, it would be fragmented
by the kernel to a size that matches the mtu on the end of the veth pair
that was in the NSC network namespace.
The resulting packet would *still* be to large for the MTU of the end of the
vethpair attached to the VPP instance, and would be dropped there.
The second fragment, being smaller, would be smaller than the MTU of the
end of the vethpair to which VPP was attached with af-packet, and so get
through.
=> Fix for mtu issues with kernelvethpair

pkg/networkservice/mechanisms/memif/client.go
Issue: https://github.com/networkservicemesh/sdk/issues/1196
We need to update `NetNSURL` for memif mechanism preference, because there might be a wrong value after previous use.
=> Update memif mechanismPreference NetNSURL on Request

pkg/networkservice/mechanisms/kernel/kerneltap/common.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go
Issue: https://github.com/networkservicemesh/sdk/issues/1196
For example, `NSMgr + NSE` died. Forwarder doesn't know about NSE death and doesn't receive `Close` from the client (because NSMgr is also died). But it stores `ifindex` in metadata that belongs to the old NSE interface.
We need to additionally check the interface by name and delete it if we find the old one.
=> Fix kernel mechanisms for healing cases

pkg/networkservice/mechanisms/memif/common.go
This is to avoid empty `SocketFilename` mechanism parameter. 
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/4219
=> [qfix] Set memif socket filename before checking

pkg/networkservice/mechanisms/vxlan/mtu/client.go, pkg/networkservice/mechanisms/vxlan/mtu/common.go, pkg/networkservice/mechanisms/vxlan/mtu/server.go, pkg/networkservice/mechanisms/wireguard/mtu/client.go, pkg/networkservice/mechanisms/wireguard/mtu/common.go, pkg/networkservice/mechanisms/wireguard/mtu/server.go, pkg/networkservice/up/client.go, pkg/networkservice/up/peerup/client.go, pkg/networkservice/up/server.go
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/2800
If context was canceled (e.g by timeout) in the middle of the chain, and the next chain element has `init` function with `sync.Once` - we have no chance to call `init` again. We store the error and all new Requests will fail with that error.
Call the `init` function only the first time, OR if the first call returned an error.
=> Fix chain elements init function

go.mod, go.sum, pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/mechanisms/memif/client.go, pkg/networkservice/mechanisms/memif/common.go, pkg/networkservice/mechanisms/memif/option.go, pkg/networkservice/mechanisms/memif/server.go
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/508
The main difference is that `MemifSocketFilenameAddDelV2` API doesn't have `Namespace` now. Instead, we should act like this: `@netns:ns0@somename`
=> Govpp update

pkg/networkservice/stats/client.go, pkg/networkservice/stats/common.go, pkg/networkservice/stats/option.go, pkg/networkservice/stats/server.go
Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/325
Needed for the case of external vpp.
=> Add an option where we can change the stats socket

.golangci.yml, go.mod, go.sum, pkg/networkservice/chains/forwarder/options.go, pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/mechanisms/vxlan/option.go
Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/325
=> Add options to the forwarder to use it with an external vpp

pkg/networkservice/loopback/client.go, pkg/networkservice/loopback/common.go, pkg/networkservice/loopback/option.go, pkg/networkservice/vrf/client.go, pkg/networkservice/vrf/common.go, pkg/networkservice/vrf/option.go
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
Requires for https://github.com/networkservicemesh/cmd-nse-vl3-vpp/pull/4
=> qfix: Add fixes after manual vl3 testing on kind

pkg/networkservice/connectioncontext/mtu/client.go, pkg/networkservice/connectioncontext/mtu/common.go, pkg/networkservice/connectioncontext/mtu/server.go, pkg/networkservice/mechanisms/vxlan/mtu/common.go, pkg/networkservice/mechanisms/wireguard/mtu/common.go
=> MTU fix for cmd-forwarder-vpp#557

pkg/networkservice/mechanisms/vlan/mtu/client.go, pkg/networkservice/mechanisms/vlan/mtu/common.go
Issue: [networkservicemesh/cmd-forwarder#557](https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/557)
Related PR: #554
The L3 MTU is set based on link L2 mtu and should not modified.
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> Fix for MTU change: get L3 mtu instead of linkMTU

go.mod, go.sum
=> Update govpp version to match cmd-forwarder-vpp#600

pkg/networkservice/mechanisms/vlan/common.go, pkg/networkservice/mechanisms/vlan/l2vtr/common.go
Fix issue: [cmd-nse-remote-vlan/18](https://github.com/networkservicemesh/cmd-nse-remote-vlan/issues/18)
Do not create vlan sub-interface when VLAN-ID is set to 0
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> Connecting a remote interface without creating a VLAN on top

.github/workflows/update-dependent-repositories-gomod.yaml
Issue: https://github.com/networkservicemesh/cmd-nsc-simple-docker/issues/1
=> Add cmd-nsc-simple-docker to dependent repositories

pkg/networkservice/chains/forwarder/options.go, pkg/networkservice/chains/forwarder/server.go
Signed-off-by: anastasia.malysheva <anastasia.malysheva@xored.com>
=> Enable authorizeMonitorConnectionServer option

pkg/networkservice/connectioncontext/ipcontext/ipaddress/client.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/server.go
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/7055
We don't need to remove the address on closing.
In most cases, Close also removes the target interface and the address will be deleted along with it.
Leaving the address allows us to solve the loopback + unnumbered problem where we don't need to remove the address when the connection is closed.
=> Don't delete ipaddress on Close

pkg/networkservice/connectioncontext/client.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/client.go, pkg/networkservice/connectioncontext/ipcontext/ipaddress/server.go, pkg/networkservice/connectioncontext/ipcontext/routes/client.go, pkg/networkservice/connectioncontext/ipcontext/routes/server.go, pkg/networkservice/connectioncontext/mtu/client.go, pkg/networkservice/connectioncontext/mtu/server.go, pkg/networkservice/connectioncontext/server.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/mtu/client.go, pkg/networkservice/mechanisms/kernel/kernelvethpair/mtu/server.go, pkg/tools/mechutils/mechutils.go, pkg/tools/types/route.go
=> Fix linter issues after update golangci-lint version

pkg/networkservice/chains/forwarder/server.go, pkg/networkservice/mechanisms/memif/client.go, pkg/networkservice/mechanisms/memif/client_test.go, pkg/networkservice/mechanisms/memif/common.go, pkg/networkservice/mechanisms/memif/memifrxmode/client.go, pkg/networkservice/mechanisms/memif/memifrxmode/common.go, pkg/networkservice/mechanisms/memif/memifrxmode/doc.go, pkg/networkservice/mechanisms/memif/memifrxmode/metadata.go, pkg/networkservice/mechanisms/memif/memifrxmode/server.go, pkg/networkservice/mechanisms/memif/server.go
Issue: https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/136
It turned out that we can set the `rx_mode` value for `memif` only after creating a connection, when the master and slave are configured and the interfaces are up. Only then does the mode setting work.
In this PR, a new chain element was added, which in the goroutine monitors events from the interface and waits `LINK_UP`. After that, sets the ADAPTIVE mode.
A new element and a goroutine were needed, since we `up` the interfaces at the last stage, when the Request has already passed the client and server.
=> Set memif_rx_mode on a separate chain element

pkg/networkservice/xconnect/l2bridgedomain/server.go
Related issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/781
=> Fix bridge setup delay for vlan mechanism

pkg/networkservice/mechanisms/kernel/kernelvethpair/afpacket/common.go
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/841
The frame size that was used in release 1.7.1 was set
=> Set Rx/TxFrameSize for af_packet interface

go.mod, go.sum, pkg/networkservice/afxdppinhole/client.go, pkg/networkservice/afxdppinhole/common.go, pkg/networkservice/afxdppinhole/doc.go, pkg/networkservice/afxdppinhole/options.go, pkg/networkservice/afxdppinhole/server.go, pkg/networkservice/chains/forwarder/server.go
This PR adds `afxdppinhole` chain element, that updates the xdp pinhole map.
On the Request, this element knows exactly which UDP ports are needed for the connection (VxLAN, Wireguard tunnels...).
This chain element updates the map that is used by the eBPF program. As a matter of fact it stores UDP ports that NSM is listening on. 
This gives us information to decide where to forward the data packet received on the interface.
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/283
=> Add afxdppinhole chain element

pkg/networkservice/chains/forwarder/server.go
This reverts commit ce2e514e2a71b25b450d83af3c7209e396b77122.
Moved to `sdk-kernel/connectioncontext` - https://github.com/networkservicemesh/sdk-kernel/pull/601
=> Revert "Add pinggrouprange to forwarder's chain (#718)"

pkg/networkservice/acl/common.go, pkg/networkservice/acl/server.go, pkg/networkservice/connectioncontext/ipcontext/routes/common.go, pkg/networkservice/up/common.go, pkg/networkservice/up/peerup/common.go, pkg/networkservice/vl3lb/common.go, pkg/networkservice/xconnect/l2bridgedomain/common.go, pkg/networkservice/xconnect/l2xconnect/common.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9726
=> Change message log level

pkg/networkservice/pinhole/client.go, pkg/networkservice/pinhole/server.go
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/927
Previously, we used `ipPortMap.LoadOrStore()` before creation. But if the `create` function returned an error, then the behavior is incorrect, since we already saved the value in the map.
=> pinhole: fix behavior in case of creation error

pkg/networkservice/acl/common.go, pkg/networkservice/acl/server.go
In the process of applying new rules, we may accidentally change the original ones
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/10319
=> Use a copy of ACLRules instead of the original

pkg/tools/heal/liveness_check.go
https://github.com/networkservicemesh/integration-k8s-kind/pull/948
=> Fix panic in vpp liveness check

pkg/networkservice/mechanisms/vxlan/common.go
VxlanAddDelTunnelV2 was deprecated (see [1]), change it to
VxlanAddDelTunnelV3 and update the related log messages also.
[1]: https://github.com/FDio/govpp/commit/8debdf0ea14b3ff9cf3877bf41f71694f76a04b0
Change-Id: I018c94c0b9d1501876c5070cb3e16733eb453506
Signed-off-by: Lajos Katona <lajos.katona@est.tech>
=> Trivial: Use VxlanAddDelTunnelV3 instead of V2

go.mod, go.sum, pkg/networkservice/mechanisms/kernel/kernelvethpair/common.go, pkg/tools/mechutils/mechutils.go
Due to dynamic name generation on the endpoint side, we can no longer rely on `mechanism.GetInterfaceName()` to remove the previous interface during healing.
Issue: https://github.com/networkservicemesh/integration-k8s-gke/issues/435
=> Fix veth-pair creation

pkg/networkservice/chains/forwarder/server.go
netNsMonitor has some bugs that make it randomly close healthy connections. So we decided to delete it and check if it affects NSM.
=> Remove netNsMonitor from forwarder-vpp

pkg/networkservice/up/peerup/common.go
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/10469610159/job/28993020446?pr=1030#step:9:3846
=> Add logs to waitForPeerUp function to see what `wireguard` events we get

go.mod, pkg/networkservice/metrics/stats/client.go, pkg/networkservice/metrics/stats/common.go, pkg/networkservice/metrics/stats/prometheus.go, pkg/networkservice/metrics/stats/server.go
Initialized Prometheus metric types and expanded current metrics to push values into Prometheus too, if enabled.
https://github.com/networkservicemesh/sdk/issues/1652
=> Add an option to expose Prometheus metrics via http/s server

.github/dependabot.yml, .github/workflows/automerge.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
This PR enables Dependabot in the repository to automatically check GitHub Actions versions weekly and create pull requests for any outdated dependencies found.
=> Enable dependabot for updating github actions
